runtime: python
env: flex

runtime_config:
    python_version: 3

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 5
                             
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  PKL_BUCKET:  'project-id.appspot.com'

