steps:
- id: 'Deploy to Environment'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'app', 
    'deploy', 
    'app.yaml',
    '--version=$BUILD_ID',
    '--no-promote',
    '--quiet'
    ]
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy app.yaml --project=angles-354211']

timeout: '1600s'

